import { 
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, 
  WidthType, BorderStyle, AlignmentType, Header, Footer, 
  PageOrientation, VerticalAlign, ImageRun 
} from 'docx';
import { format, parseISO, startOfDay, addDays, differenceInDays, isBefore } from 'date-fns';
import { supabase } from '../lib/supabase';

const FONT = "Helvetica"; // ISSUE 10: Swapped to Helvetica for universal OS compatibility
const COLORS = { 
  text: "000000", meta: "555555", border: "A3A3A3", headerBg: "EFEFEF", highlight: "0055A4"
};

const BORDER_STYLE = { style: BorderStyle.SINGLE, size: 2, color: COLORS.border };
const TABLE_BORDERS = { 
  top: BORDER_STYLE, bottom: BORDER_STYLE, 
  left: BORDER_STYLE, right: BORDER_STYLE, 
  insideHorizontal: BORDER_STYLE, insideVertical: BORDER_STYLE 
};

const getOrgProfile = async () => {
  try {
    const { data } = await supabase.from('organization_profile').select('org_name, address').eq('is_deleted', false).limit(1).single();
    return data || { org_name: "CLINICAL DISPENSARY", address: "" };
  } catch {
    return { org_name: "CLINICAL DISPENSARY", address: "" };
  }
};

const getLogoBuffer = async (): Promise<ArrayBuffer | null> => {
  if (!navigator.onLine) return null;
  try {
    const { data } = await supabase.storage.from('koa-attachments').download('logos/primary-logo.jpeg');
    return data ? await data.arrayBuffer() : null;
  } catch {
    return null;
  }
};

const triggerNativeDownload = (blob: Blob, filename: string) => {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.target = '_blank'; // ISSUE 12: Prevents block failures in sandboxed iframe previews
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { document.body.removeChild(a); window.URL.revokeObjectURL(url); }, 150);
};

const getDoseRows = (freq: string) => {
  switch (freq) {
    case 'BID': return ['AM Dose', 'PM Dose'];
    case 'TID': return ['Dose 1', 'Dose 2', 'Dose 3'];
    case 'QID': return ['Dose 1', 'Dose 2', 'Dose 3', 'Dose 4'];
    case 'PRN': return ['PRN 1', 'PRN 2', 'PRN 3'];
    default: return ['Daily Dose'];
  }
};

export const marExportService = {
  async exportUnifiedMAR(animal: any, prescriptions: any[], generatorName: string, generatorId: string) {
    const [logoBuffer, orgProfile] = await Promise.all([getLogoBuffer(), getOrgProfile()]);
    const today = startOfDay(new Date());

    const documentHeader = new Header({
      children: [
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE }, insideVertical: { style: BorderStyle.NONE }, insideHorizontal: { style: BorderStyle.NONE } },
          rows: [
            new TableRow({
              children: [
                new TableCell({
                  width: { size: 40, type: WidthType.PERCENTAGE },
                  children: logoBuffer ? [new Paragraph({ children: [new ImageRun({ data: logoBuffer, transformation: { width: 100, height: 75 } } as any)] })] : [new Paragraph("")]
                }),
                new TableCell({
                  width: { size: 60, type: WidthType.PERCENTAGE },
                  children: [
                    new Paragraph({ children: [new TextRun({ text: orgProfile.org_name.toUpperCase(), bold: true, size: 28, color: COLORS.text, font: FONT })], alignment: AlignmentType.RIGHT }),
                    new Paragraph({ children: [new TextRun({ text: orgProfile.address || '', size: 20, color: COLORS.meta, font: FONT })], alignment: AlignmentType.RIGHT })
                  ]
                })
              ]
            })
          ]
        }),
        new Paragraph({ text: "", spacing: { before: 400, after: 200 } }) 
      ]
    });

    const documentFooter = new Footer({
      children: [
        new Paragraph({
          children: [
            new TextRun({ text: `Exception Codes: `, bold: true, size: 18, font: FONT }),
            new TextRun({ text: `R = Refused | V = Vomited | S = Spit/Dropped | N/A = Not Available | O = Omitted | H = Hospitalized`, size: 18, color: COLORS.meta, font: FONT })
          ],
          alignment: AlignmentType.CENTER,
          spacing: { after: 120 }
        }),
        new Paragraph({
          children: [
            new TextRun({ text: `Generated by: ${generatorName} [${generatorId}] on ${format(new Date(), 'dd MMM yyyy HH:mm')}`, size: 16, color: COLORS.meta, font: FONT })
          ],
          alignment: AlignmentType.CENTER
        })
      ]
    });

    const createWeekTable = (weekDates: Date[], doses: string[]) => {
      const totalDoseRows = doses.length * 2; 
      const daysCount = weekDates.length;
      
      const taskWidth = 15;
      const notesWidth = 20;
      const dayWidth = (100 - taskWidth - notesWidth) / daysCount;

      const rows: TableRow[] = [];
      
      const headerCells = [
        new TableCell({ width: { size: taskWidth, type: WidthType.PERCENTAGE }, shading: { fill: COLORS.headerBg }, margins: { top: 80, bottom: 80 }, children: [new Paragraph({ children: [new TextRun({ text: "Task", bold: true, size: 16, font: FONT })], alignment: AlignmentType.CENTER })] }),
        ...weekDates.map(d => new TableCell({ width: { size: dayWidth, type: WidthType.PERCENTAGE }, shading: { fill: COLORS.headerBg }, margins: { top: 80, bottom: 80 }, children: [new Paragraph({ children: [new TextRun({ text: format(d, 'dd/MM'), bold: true, size: 16, font: FONT })], alignment: AlignmentType.CENTER })] })),
        new TableCell({ width: { size: notesWidth, type: WidthType.PERCENTAGE }, shading: { fill: COLORS.headerBg }, margins: { top: 80, bottom: 80 }, children: [new Paragraph({ children: [new TextRun({ text: "Daily Notes", bold: true, size: 16, font: FONT })], alignment: AlignmentType.CENTER })] })
      ];
      rows.push(new TableRow({ tableHeader: true, children: headerCells }));

      doses.forEach((doseLabel, doseIndex) => {
        const timeCells: TableCell[] = [];
        timeCells.push(new TableCell({ margins: { top: 100, bottom: 100 }, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ children: [new TextRun({ text: `${doseLabel}\n(Time)`, size: 14, font: FONT, color: COLORS.meta })], alignment: AlignmentType.CENTER })] }));
        weekDates.forEach(() => { timeCells.push(new TableCell({ children: [new Paragraph("")] })); });
        if (doseIndex === 0) timeCells.push(new TableCell({ rowSpan: totalDoseRows, margins: { top: 100, bottom: 100 }, children: [new Paragraph("")] }));
        rows.push(new TableRow({ children: timeCells }));

        const initialCells: TableCell[] = [];
        initialCells.push(new TableCell({ margins: { top: 100, bottom: 100 }, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ children: [new TextRun({ text: "Initials", size: 14, font: FONT, bold: true })], alignment: AlignmentType.CENTER })] }));
        weekDates.forEach(() => { initialCells.push(new TableCell({ children: [new Paragraph("")] })); });
        rows.push(new TableRow({ children: initialCells }));
      });

      return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, borders: TABLE_BORDERS, rows });
    };

    const documentBody: any[] = [
      new Paragraph({ children: [new TextRun({ text: `MEDICATION ADMINISTRATION RECORD`, bold: true, size: 28, font: FONT })], spacing: { after: 120 } }),
      new Paragraph({ children: [new TextRun({ text: `Patient: ${animal?.name || 'Unknown'} (${animal?.species || 'Unknown'}) | ID: ${animal?.id?.substring(0,8).toUpperCase() || 'N/A'} | Location: ${animal?.location || 'Unassigned'}`, size: 20, color: COLORS.meta, font: FONT, bold: true })], spacing: { after: 400 } }),
    ];

    if (prescriptions.length === 0) {
      documentBody.push(new Paragraph({ children: [new TextRun({ text: "No Active Prescriptions Found.", color: COLORS.meta, font: FONT, italics: true })] }));
    } else {
      
      prescriptions.forEach((rx) => {
        const rxStart = rx.start_date ? startOfDay(parseISO(rx.start_date)) : today;
        // ISSUE 7: Capped print window relative to today to preserve usefulness of ongoing/historic prints
        const windowStart = isBefore(rxStart, today) ? startOfDay(today) : rxStart;
        let rxEnd = rx.end_date ? startOfDay(parseISO(rx.end_date)) : addDays(windowStart, 27); 
        
        if (isBefore(rxEnd, windowStart)) rxEnd = windowStart; 

        if (differenceInDays(rxEnd, windowStart) > 31) {
          rxEnd = addDays(windowStart, 30);
        }

        const totalDays = differenceInDays(rxEnd, windowStart) + 1;
        const rxDates = Array.from({ length: totalDays }, (_, i) => addDays(windowStart, i));
        
        const weeklyChunks = [];
        for (let i = 0; i < rxDates.length; i += 7) weeklyChunks.push(rxDates.slice(i, i + 7));

        documentBody.push(new Paragraph({
            spacing: { before: 400, after: 80 },
            children: [
                new TextRun({ text: `${rx.drug_name} `, bold: true, size: 24, font: FONT }),
                new TextRun({ text: `(${rx.dosage})`, color: COLORS.highlight, bold: true, size: 20, font: FONT })
            ]
        }));
        
        documentBody.push(new Paragraph({
            spacing: { after: 120 },
            children: [
                new TextRun({ text: `Route: ${rx.route} | Frequency: ${rx.frequency} ${rx.is_prn ? '(PRN)' : ''}`, size: 16, font: FONT }),
                new TextRun({ text: `  •  Period: ${format(rxStart, 'dd/MM/yy')} to ${rx.end_date ? format(rxEnd, 'dd/MM/yy') : 'Ongoing'}`, size: 16, color: COLORS.meta, font: FONT })
            ]
        }));

        if (rx.special_instructions) {
           documentBody.push(new Paragraph({
               spacing: { after: 200 },
               children: [new TextRun({ text: `Instructions: ${rx.special_instructions}`, italics: true, size: 16, color: "FF0000", font: FONT })]
           }));
        }

        weeklyChunks.forEach((chunkDates) => {
            documentBody.push(createWeekTable(chunkDates, getDoseRows(rx.frequency)));
            documentBody.push(new Paragraph({ spacing: { after: 200 }, text: "" })); 
        });
        
        documentBody.push(new Paragraph({ border: { bottom: { color: "E2E8F0", space: 1, style: BorderStyle.SINGLE, size: 6 } }, spacing: { after: 200 } }));
      });
    }

    const doc = new Document({
      sections: [{
        properties: { 
          page: { size: { orientation: PageOrientation.PORTRAIT }, margin: { top: 720, bottom: 720, left: 720, right: 720 } } 
        },
        headers: { default: documentHeader },
        footers: { default: documentFooter },
        children: documentBody
      }]
    });

    await new Promise(resolve => setTimeout(resolve, 50));
    
    const blob = await Packer.toBlob(doc);
    triggerNativeDownload(blob, `MAR_${animal?.name?.replace(/\s+/g, '_') || 'Patient'}_${format(new Date(), 'yyyyMMdd')}.docx`);
  }
};